allowBuilds:
  core-js: false
  msw: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - hwagfu-link
  - hwagfu-cursor@0.1.0
  - '@hwagfu/cursor@1.2.0'
overrides:
  hwagfu-quick-link: link:../../jasoncomponent
