import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navigation } from "@/components/Naviagtion";
import { Toast } from "@heroui/react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toast.Provider placement="top end"/>
        <Navigation />
        <main>
          {children}
        </main>
        <footer className="py-12 border-t border-gray-100 bg-white">
        <div className="max-w-7xl mx-auto px-8 flex flex-col md:flex-row justify-between items-center gap-6">
          <p className="text-sm text-[#6F6F6F]">
            © {new Date().getFullYear()} Phan Hoàng Phúc. All rights reserved.
          </p>
          <div className="flex gap-8">
            <a href="#" className="text-sm text-[#6F6F6F] hover:text-black transition-colors">GitHub</a>
            <a href="#" className="text-sm text-[#6F6F6F] hover:text-black transition-colors">LinkedIn</a>
            <a href="#" className="text-sm text-[#6F6F6F] hover:text-black transition-colors">Twitter</a>
          </div>
        </div>
      </footer>
      </body>
      
    </html>
  );
}
