"use client";
/*
 * Link preview — generated by microlink.io/integrations/builder
 * Zero dependencies, fully typed. Drop this file in and render it with a url.
 * Styled with Tailwind CSS — include this file in your Tailwind 'content'
 * config (Tailwind v3.3+) so the classes below are generated.
 *
 *   import LinkPreview from './LinkPreview'
 *
 *   <LinkPreview url='https://github.com' />
 *   <LinkPreview url='https://github.com' apiKey='YOUR_KEY' />   // Pro
 */
import { useEffect, useState } from 'react'

type LinkPreviewProps = {
  url: string
  apiKey?: string
}

const STYLE = {
  "variant": "small",
  "elements": {
    "description": true,
    "siteIcon": true,
    "siteName": true,
    "authorTopic": false,
    "date": false
  },
  "metaBefore": true,
  "titleLimit": 60,
  "descLimit": 140,
  "frameClass": "flex no-underline text-inherit gap-[10px] items-start w-full max-w-[360px] px-[14px] py-[12px] rounded-[20px] bg-[#ffffff] border-[0px] border-solid border-[#dedede] shadow-[0_1px_4px_rgba(0,0,0,0.1)] font-sans",
  "iconClass": "w-[36px] h-[36px] rounded-[8px] shrink-0",
  "iconBoxClass": "w-[36px] h-[36px] rounded-[8px] shrink-0",
  "contentClass": "flex-1 min-w-0",
  "metaRowClass": "flex items-center justify-between mb-[2px] gap-[8px]",
  "metaInnerClass": "flex items-center gap-[4px] min-w-0 overflow-hidden",
  "publisherClass": "text-[12px] font-normal text-[#999999]",
  "authorDotClass": "text-[11px] text-[#999999]",
  "authorClass": "text-[11px] text-[#999999]",
  "dateClass": "text-[11px] text-[#999999]",
  "titleClass": "text-[11px] font-normal text-[#000000] leading-[1.4] mb-[2px]",
  "descriptionClass": "text-[11px] text-[#000000] leading-[1.4] line-clamp-2"
}

function escA (v: any) {
  return String(v == null ? '' : v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
function escT (v: any) {
  return String(v == null ? '' : v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
function trunc (t: any, max: any) {
  var str = String(t == null ? '' : t)
  if (!max || str.length <= max) return str
  var slice = str.slice(0, max - 1)
  var trimmed = slice.replace(/\s+\S*$/, '')
  return (trimmed || slice) + '…'
}
function fmtDate (v: any) {
  if (!v) return ''
  try {
    var d = new Date(v)
    if (isNaN(d.getTime())) return ''
    return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })
  } catch (e) { return '' }
}
function fallbackBg (data: any) {
  return (data.image && data.image.palette && data.image.palette[0]) || 'rgba(0,0,0,0.05)'
}
function logoFallbackAttr (logoUrl: any) {
  return logoUrl ? 'onerror="this.onerror=null;this.src=\'' + logoUrl.replace(/'/g, '&#39;') + '\';this.style.objectFit=\'contain\';this.style.padding=\'15%\'" ' : ''
}
function buildMeta (data: any, s: any) {
  var pieces = []
  if (s.elements.siteIcon && data.logo && data.logo.url) {
    pieces.push('<img class="' + s.metaIconClass + '" src="' + escA(data.logo.url) + '" alt="" />')
  }
  if (s.elements.siteName && data.publisher) {
    pieces.push('<span class="' + s.metaNameClass + '">' + escT(data.publisher) + '</span>')
  }
  if (s.elements.authorTopic && data.author) {
    pieces.push('<span class="' + s.metaAuthorClass + '">' + escT(data.author) + '</span>')
  }
  if (s.elements.date && data.date) {
    var dateStr = fmtDate(data.date)
    if (dateStr) {
      pieces.push('<span class="' + s.metaDateClass + '">' + escT(dateStr) + '</span>')
    }
  }
  if (!pieces.length) return ''
  return '<div class="' + s.metaWrapClass + '">' + pieces.join('') + '</div>'
}
function buildStandard (data: any, s: any) {
  var href = escA((data && data.url) || '')
  var imageUrl = (data.image && data.image.url) ? escA(data.image.url) : ''
  var logoUrl = (data.logo && data.logo.url) ? escA(data.logo.url) : ''
  var title = escT(trunc((data && data.title) || '', s.titleLimit))
  var description = s.elements.description ? escT(trunc((data && data.description) || '', s.descLimit)) : ''
  var bg = escA(fallbackBg(data))
  var metaHtml = buildMeta(data, s)
  var mediaInner = imageUrl ? '<img class="w-full h-full object-cover block" src="' + imageUrl + '" alt="" ' + logoFallbackAttr(logoUrl) + '/>' : ''
  var titleHtml = '<div class="' + s.titleClass + '">' + title + '</div>'
  var descriptionHtml = description ? '<div class="' + s.descriptionClass + '">' + description + '</div>' : ''
  var body = s.metaBefore ? (metaHtml + titleHtml + descriptionHtml) : (titleHtml + descriptionHtml + metaHtml)
  return '<a class="' + s.frameClass + '" href="' + href + '" target="_blank" rel="noopener noreferrer">' +
    '<div class="' + s.mediaBoxClass + '" style="background:' + bg + '">' + mediaInner + '</div>' +
    '<div class="' + s.bodyClass + '">' + body + '</div></a>'
}
function buildSmall (data: any, s: any) {
  var href = escA((data && data.url) || '')
  var logoUrl = (data.logo && data.logo.url) ? escA(data.logo.url) : ''
  var title = escT(trunc((data && data.title) || '', s.titleLimit))
  var description = s.elements.description ? escT(trunc((data && data.description) || '', s.descLimit)) : ''
  var bg = escA(fallbackBg(data))
  var iconNode = !s.elements.siteIcon ? '' : (logoUrl ? '<img class="' + s.iconClass + '" src="' + logoUrl + '" alt="" />' : '<div class="' + s.iconBoxClass + '" style="background:' + bg + '"></div>')
  var publisherText = (s.elements.siteName && data.publisher) ? '<span class="' + s.publisherClass + '">' + escT(data.publisher) + '</span>' : ''
  var authorText = (s.elements.authorTopic && data.author) ? '<span aria-hidden="true" class="' + s.authorDotClass + '">· </span><span class="' + s.authorClass + '">' + escT(data.author) + '</span>' : ''
  var dateText = (s.elements.date && data.date) ? '<span class="' + s.dateClass + '">' + escT(fmtDate(data.date)) + '</span>' : ''
  var metaRow = (publisherText || authorText) ? '<div class="' + s.metaRowClass + '"><span class="' + s.metaInnerClass + '">' + publisherText + authorText + '</span>' + dateText + '</div>' : ''
  var titleHtml = '<div class="' + s.titleClass + '">' + title + '</div>'
  var descriptionHtml = description ? '<div class="' + s.descriptionClass + '">' + description + '</div>' : ''
  var body = s.metaBefore ? (metaRow + titleHtml + descriptionHtml) : (titleHtml + descriptionHtml + metaRow)
  return '<a class="' + s.frameClass + '" href="' + href + '" target="_blank" rel="noopener noreferrer">' + iconNode + '<div class="' + s.contentClass + '">' + body + '</div></a>'
}
function renderCard (data: any, s: any) {
  if (!data) return ''
  if (s.variant === 'small') return buildSmall(data, s)
  return buildStandard(data, s)
}

function withProtocol (url: any) {
  var str = String(url == null ? '' : url).trim()
  if (!str || /^https?:\/\//i.test(str)) return str
  var normalized = 'https://' + str.replace(/^\/+/, '')
  console.warn('[microlink] "' + str + '" has no protocol — assuming "' + normalized + '". Pass a full URL with an explicit https:// (or http://) to avoid this.')
  return normalized
}
function microlinkFetch (url: any, apiKey: any) {
  var endpoint = apiKey ? 'https://pro.microlink.io/' : 'https://api.microlink.io/'
  var qs = new URLSearchParams({ url: withProtocol(url), palette: 'true' }).toString()
  return fetch(endpoint + '?' + qs)
    .then(function (r: any) { return r.ok ? r.json() : null })
    .then(function (res: any) { return res && res.data })
    .catch(function () { return null })
}

export default function LinkPreview ({ url, apiKey }: LinkPreviewProps) {
  const [html, setHtml] = useState('')

  useEffect(() => {
    let active = true
    microlinkFetch(url, apiKey).then(data => {
      if (active && data) setHtml(renderCard(data, STYLE))
    })
    return () => { active = false }
  }, [url, apiKey])

  return <div dangerouslySetInnerHTML={{ __html: html }} />
}